# Generated by Django 5.1.3 on 2024-12-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "This email has already been registered."},
                max_length=254,
                unique=True,
            ),
        ),
    ]
