# Generated by Django 5.1.3 on 2024-12-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingprocess",
            name="active_subscription",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="onboardingprocess",
            name="authenticated",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="onboardingprocess",
            name="level_4_permission",
            field=models.BooleanField(null=True),
        ),
    ]
