# Generated by Django 5.1.3 on 2024-12-09 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("ibkr", "0002_alter_onboardingprocess_active_subscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingprocess",
            name="periodic_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
