# Generated by Django 5.1.3 on 2024-12-18 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0003_onboardingprocess_periodic_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("instrument", models.CharField(max_length=100)),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("EQUITY", "equity"),
                            ("COMMODITY", "commodity"),
                            ("CRYPTO", "crypto"),
                        ],
                        max_length=100,
                    ),
                ),
                ("instrument_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SystemData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("analysis_time", models.IntegerField(blank=True, null=True)),
                (
                    "time_frame",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-day", "1d"),
                            ("4-hours", "4h"),
                            ("1-hour", "1h"),
                            ("30-min", "30min"),
                            ("15-min", "15min"),
                            ("5-min", "5min"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("time_steps", models.IntegerField(blank=True, null=True)),
                ("confidence_level", models.IntegerField(blank=True, null=True)),
                ("contract_expiry", models.IntegerField(blank=True, null=True)),
                (
                    "contract_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("no_of_contracts", models.IntegerField(blank=True, null=True)),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[("call", "Call"), ("put", "Put"), ("both", "Both")],
                        max_length=4,
                        null=True,
                    ),
                ),
                ("upper_bound", models.FloatField(blank=True, null=True)),
                ("lower_bound", models.FloatField(blank=True, null=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ibkr.instrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderData",
            fields=[
                (
                    "systemdata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ibkr.systemdata",
                    ),
                ),
                ("limit_sell", models.FloatField()),
                ("limit_buy", models.FloatField()),
                ("stop_loss", models.FloatField()),
                ("take_profit", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
            bases=("ibkr.systemdata",),
        ),
        migrations.CreateModel(
            name="TimerData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("timer_value", models.IntegerField()),
                ("start_time", models.TimeField()),
                ("place_order", models.BooleanField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TradingStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("status", models.CharField(blank=True, max_length=1, null=True)),
                ("wait_time", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
