# Generated by Django 5.1.3 on 2024-12-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0004_instrument_systemdata_orderdata_timerdata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrument",
            name="conid",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="exchange",
        ),
        migrations.AddField(
            model_name="instrument",
            name="instrument_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
