# Generated by Django 5.1.3 on 2024-12-18 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0004_instrument_systemdata_orderdata_timerdata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timerdata",
            name="user",
        ),
        migrations.AddField(
            model_name="systemdata",
            name="range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ibkr.timerdata",
            ),
        ),
    ]
