# Generated by Django 5.1.3 on 2024-12-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0005_remove_instrument_conid_remove_instrument_exchange_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timerdata",
            name="is_active",
        ),
        migrations.AddField(
            model_name="timerdata",
            name="place_order",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timerdata",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
