# Generated by Django 5.1.3 on 2024-12-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0005_remove_timerdata_user_systemdata_range"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrument",
            name="instrument_data",
        ),
        migrations.AddField(
            model_name="systemdata",
            name="instrument_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
