# Generated by Django 5.1.4 on 2024-12-18 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0007_alter_systemdata_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemdata',
            old_name='range',
            new_name='timer',
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('accountId', models.CharField(max_length=100)),
                ('conid', models.IntegerField()),
                ('orderType', models.CharField(choices=[('LMT', 'LMT'), ('MKT', 'MKT')], max_length=4)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('tif', models.CharField(choices=[('DAY', 'DAY'), ('GTC', 'GTC'), ('OPG', 'OPG'), ('IOC', 'IOC'), ('GTD', 'GTD'), ('FOK', 'FOK'), ('DTC', 'DTC')], max_length=4)),
                ('quantity', models.IntegerField()),
                ('exp_date', models.CharField(blank=True, max_length=8, null=True)),
                ('exp_time', models.CharField(blank=True, max_length=8, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
