# Generated by Django 5.1.3 on 2024-12-18 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0008_rename_range_systemdata_timer_placeorder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemdata",
            old_name="instrument_data",
            new_name="ticker_data",
        ),
    ]
