# Generated by Django 5.1.4 on 2024-12-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0008_rename_range_systemdata_timer_placeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='limit_buy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='limit_sell',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='stop_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='take_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrderData',
        ),
    ]
