# Generated by Django 5.1.3 on 2024-12-18 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0010_timerdata_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemdata",
            name="timer",
        ),
    ]
