# Generated by Django 5.1.3 on 2024-12-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0012_placeorder_limit_buy_placeorder_limit_sell_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timerdata",
            name="original_timer_value",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
