# Generated by Django 5.1.3 on 2024-12-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0013_timerdata_original_timer_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeorder",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemdata",
            name="time_frame",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-day", "1d"),
                    ("4-hours", "4h"),
                    ("1-hour", "1h"),
                    ("30-mins", "30min"),
                    ("15-mins", "15min"),
                    ("5-mins", "5min"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
