# Generated by Django 5.1.3 on 2024-12-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0015_strikes"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemdata",
            name="contract_trading_months",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="strikes",
            name="is_valid",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
