# Generated by Django 5.1.3 on 2024-12-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0016_systemdata_contract_trading_months_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strikes",
            name="month",
        ),
        migrations.AddField(
            model_name="strikes",
            name="right",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
