# Generated by Django 5.1.3 on 2024-12-24 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0017_remove_strikes_month_strikes_right"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strikes",
            name="maturity_date",
        ),
    ]
