# Generated by Django 5.1.3 on 2024-12-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0018_remove_strikes_maturity_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="strikes",
            name="month",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
