# Generated by Django 5.1.3 on 2024-12-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0019_strikes_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemdata",
            name="form_step",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
