# Generated by Django 5.1.3 on 2024-12-30 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("ibkr", "0020_systemdata_form_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemdata",
            name="validate_strikes_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
