# Generated by Django 5.1.3 on 2024-12-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0021_systemdata_validate_strikes_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placeorder",
            name="exp_date",
        ),
        migrations.RemoveField(
            model_name="placeorder",
            name="exp_time",
        ),
        migrations.RemoveField(
            model_name="placeorder",
            name="limit_buy",
        ),
        migrations.AddField(
            model_name="placeorder",
            name="optionType",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="placeorder",
            name="order_api_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="placeorder",
            name="orderType",
            field=models.CharField(
                choices=[("LMT", "LMT"), ("MKT", "MKT"), ("STP", "STP")], max_length=4
            ),
        ),
    ]
