# Generated by Django 5.1.3 on 2025-01-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0022_remove_placeorder_exp_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeorder",
            name="customer_order_id",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
