# Generated by Django 5.1.3 on 2025-01-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0023_placeorder_customer_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeorder",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
