# Generated by Django 5.1.3 on 2025-01-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0024_placeorder_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timerdata",
            name="place_order",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
