# Generated by Django 5.1.3 on 2025-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0027_alter_systemdata_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="timerdata",
            name="original_time_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
