# Generated by Django 5.1.3 on 2025-01-13 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibkr", "0028_timerdata_original_time_start"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="strikes",
            name="strike_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="strikes",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
