# Generated by Django 5.1.5 on 2025-01-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0030_systemdata_contract_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='order_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
