# Generated by Django 5.1.5 on 2025-01-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0031_placeorder_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeorder',
            old_name='is_deleted',
            new_name='is_cancelled',
        ),
    ]
