# Generated by Django 5.1.5 on 2025-01-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0032_rename_is_deleted_placeorder_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='average_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='con_desc2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
