# Generated by Django 5.1.5 on 2025-02-03 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0033_placeorder_average_price_placeorder_con_desc2'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='system_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibkr.systemdata'),
        ),
    ]
