# Generated by Django 5.1.5 on 2025-02-05 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0034_placeorder_system_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerdata',
            name='system_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibkr.systemdata'),
        ),
    ]
