# Generated by Django 5.1.5 on 2025-02-06 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0035_timerdata_system_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='system_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibkr.systemdata'),
        ),
    ]
